Neuer Link Nutzungsbedingungen
europace/baufismart-ereignisse-api pull request #18
Opened 2020-09-17 13:43 UTC by MikeKrueger75

Link Nutzungsbedingungen auf neue Website umgestellt

2020-09-18 05:24 UTC, uweelsholz requested changes
Danke fürs Aufräumen! Kannst Du bitte gleich noch das `:warning:` entfernen, dann gibt's auch umgehend das Approval 👍

2020-09-18 05:24 UTC, uweelsholz commented on README.md
> +> :warning: Diese Schnittstelle wird kontinuierlich weiterentwickelt. Daher erwarten wir
```suggestion
> Diese Schnittstelle wird kontinuierlich weiterentwickelt. Daher erwarten wir
```
`:warning:` wird von der neuen API-Seite nicht korrekt gerendert

2020-10-20 08:23 UTC, mdehmel approved these changes
Sorry, der Review-Request ist untergegangen. Hab ihn gerade eher zufällig gefunden.

2020-10-20 08:27 UTC, uweelsholz approved these changes

2020-10-20 08:29 UTC, merged